namespace YuSheng.OrchardCore.ReCaptcha.SixLabors.ViewModels
{
    public class SixLaborsCaptchaSettingsViewModel
    {
        public int IpDetectionThreshold { get; set; }
        //Number of CAPTCHA codes generated by default
        public int NumberOfCaptcha { get; set; } = 6;
        public bool SettingsAreConfigured { get; set; }
 
    }
}
